# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
#  command = "bin/netlify.sh"
# publish = "exampleSite/public"
   command = "bin/netlify-production.sh"
   publish = "exampleSite/public/"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "exampleSite/public/"
  command = "bin/netlify.sh"
