# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
#  command = "bin/netlify-production.sh"
#  publish = "exampleSite/dist"
   publish = "exampleSite/public/"
   command = "bin/netlify.sh"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "exampleSite/public/"
  command = "bin/netlify.sh"
