# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Castanet"
license = "MIT"
licenselink = "https://github.com/mattstratton/castanet/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18
theme_version = 0.2.2

[author]
  name = "Matt Stratton"
  homepage = "https://www.mattstratton.io"
