# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Castanet"
license = "MIT"
licenselink = "https://github.com/mattstratton/castanet/blob/master/LICENSE.md"
description = "A podcast-oriented theme for Hugo"
homepage = "https://github.com/mattstratton/castanet"
tags = ["podcast", "responsive"]
features = ["podcast RSS", "subscribe buttons"]
min_version = 0.36
theme_version = "0.9.1"

[author]
  name = "Matt Stratton"
  homepage = "https://www.mattstratton.io"
