baseurl = "http://sample-castanet.netlify.com/"
languageCode = "en-us"
title = "HugoCast"
theme = "castanet"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# SectionPagesMenu = "Main"
# About section of menu
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "/books"
    parent = "resources"

[params]
homepage = "http://sample-castanet.netlify.com" # must not end with a slash
copyright_notice = "Copyright 2016 [Matt Stratton](https://www.mattstrattion.io)"
itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about [podcasting](https://en.wikipedia.org/wiki/Podcast) from the most inspiring experts to ever show up on the whole internet."
media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
  [params.feed]
    feed_copyright = "Copyright 2016 Matt Stratton" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "Matt Stratton" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    github = "arresteddevops"
    facebook = "Arresteddevops"
    facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    twitter = "arresteddevops"
    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "ArrestedDevOps"
    pinterest = "nozzleio"
    instagram = "nozzleio"
    youtube = "arresteddevops"
    linkedin = "mattstratton"

  [params.authors]
    [params.authors.Matt]
      name	= "Matt Stratton"
      thumbnail = "https://www.arresteddevops.com/img/matt.png"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.Matt.social]
        github = "mattstratton"
        facebook = "matt.stratton"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.io"
    [params.authors.Trevor]
			name = "Trevor Hess"
			thumbnail = "https://www.arresteddevops.com/img/trevor.png"
			bio = ""
				[params.authors.Trevor.social]
					twitter = "trevorghess"
